Change libusb to libusb1 in pinebook keyboard updater
This error is shown after updating to nixos 24.11
> error: 'libusb' has been renamed to/replaced by 'libusb1'